### PR TITLE
gracefully recover from the lack of a gravatar

### LINKED ISSUE #24: if user has no gravatar for their LG default email address, they cannot sign-in to echo
```
Jun 24 14:06:44 echo app/web.1:  [LG SSO] found user, updating Rocket.Chat user info 
Jun 24 14:06:44 echo app/web.1:  [LG SSO] setting avatar from gravatar 
Jun 24 14:06:44 echo app/web.1:  Error while handling the setting of the avatar from a url (https://secure.gravatar.com/avatar/48e6c07c5ca7ce9ecdb4be6ec0400d80?default=404&size=200) for prattsj: { [Error: failed [404] 404 Not Found] stack: [Getter] } 
Jun 24 14:06:44 echo app/web.1:  [LG SSO] invalid or expired lgJWT token TypeError: string is not a function 
Jun 24 14:06:44 echo app/web.1:      at [object Object].Meteor.methods.setAvatarFromService (server/methods/setAvatarFromService.coffee:22:109) 
Jun 24 14:06:44 echo app/web.1:      at [object Object].methodsMap.(anonymous function) (server/lib/debug.js:17:26) 
Jun 24 14:06:44 echo app/web.1:      at maybeAuditArgumentChecks (livedata_server.js:1698:12) 
Jun 24 14:06:44 echo app/web.1:      at livedata_server.js:1611:18 
Jun 24 14:06:44 echo app/web.1:      at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) 
Jun 24 14:06:44 echo app/web.1:      at [object Object]._.extend.apply (livedata_server.js:1610:45) 
Jun 24 14:06:44 echo app/web.1:      at [object Object]._.extend.call (livedata_server.js:1553:17) 
Jun 24 14:06:44 echo app/web.1:      at [object Object].<anonymous> (server/sso.js:73:12) 
Jun 24 14:06:44 echo app/web.1:      at packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:186:1 
Jun 24 14:06:44 echo app/web.1:      at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1) 
Jun 24 14:06:44 echo app/web.1:      at Object.Meteor.runAsUser (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:185:1) 
Jun 24 14:06:44 echo app/web.1:      at setAvatarFromGravatar (server/sso.js:69:10) 
Jun 24 14:06:44 echo app/web.1:      at createOrUpdateUserFromJWT (server/sso.js:114:3) 
```

### PR DESCRIPTION
**Pull request by jeffreywescott**
Fixes #24.
1. Set the default to an initials image URL (from our initials service).
2. Ensure that non-fatal errors do not hinder the authentication process. For example, joining default rooms, setting the avatar, etc. The only things that should fail the sign-in process are (a) token errors, and (b) low-level Meteor / MongoDB errors.

### CODE REVIEW

**Comment by heyheyjp** [comment]
LGTM 👍

File: server/sso.js [hunk 1]
```diff
@@ -65,11 +65,12 @@ function joinRooms(rcUser) {
   }
 }
 
-function setAvatarFromGravatar(rcUser, email) {
+function setAvatarFromGravatar(rcUser, lgUser) {
   Meteor.runAsUser(rcUser._id, () => {
     console.log('[LG SSO] setting avatar from gravatar')
     /* global Gravatar */
-    const url = Gravatar.imageUrl(email, {default: '404', size: 200, secure: true})
+    const defaultURL = encodeURIComponent(`https://lg-initials-avatar.herokuapp.com/${lgUser.name}`)
```
Comment (heyheyjp) [inline server/sso.js:72]: Ideally would pass this in as a config option from the consuming code, but OK for now. :)

**Comment by jeffreywescott** [comment]
Coo.l Thanks for the review. Gonna merge (since it makes things better, not worse). We can address configuration stuff within echo-chat in another PR.
