### PR TITLE
echo SSO fixes

### LINKED ISSUE #26: if no gravatar, sign-in to echo sometimes fails

### LINKED ISSUE #27: any authentication errors should display an error to the user and redirect them back to IDM
identity_management_and_any_authentication_errors_should_display_an_error_to_the_user_and_redirect_them_back_to_idm_ _issue__27_ _learnersguild_rocketchat-lg-sso_and_meteor_accounts_client_js_at_devel_ _meteor_meteor

### PR DESCRIPTION
**Pull request by jeffreywescott**
Fixes #26 (use GitHub avatar instead of Gravatar)
Fixes #27 (redirect to IDM [with an error] if login fails for any reason)

### CODE REVIEW

File: client/sso.js [hunk 1]
```diff
@@ -34,6 +34,10 @@ function formatUrl(urlObject) {
   return url
 }
 
+function idmURL() {
+  return window.location.href.match(/learnersguild\.dev/) ? 'http://idm.learnersguild.dev' : 'https://idm.learnersguild.org'
```
Comment (bundacia) [inline client/sso.js:38]: Is there any way to pull this from config?

**Comment by bundacia** [comment]
Looks good. Just had one question about config.

**Comment by jeffreywescott** [comment]
@bundacia: tracked here https://github.com/LearnersGuild/echo-chat/issues/24 -- I don't want to introduce any further code changes at this point, but we can revisit later.
